spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  elasticsearch:
    host: localhost
    port: 9200

#阿里百炼大模型
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: 111
        model-name: qwen-flash
      embedding-model:
        api-key: 111
        model-name: text-embedding-v4
      streaming-chat-model:
        api-key: 111
        model-name: qwen-flash

#pinecone向量数据库
pineconeEmbeddingStore:
  apiKey: pcsk_mSRVo_HZfUw6iKbdT235owE7Ry994UjvFsWQ35N3h6ALsGhWCtCnV8dqympKoAfEKYWCN
  index: xiaobao-index
  nameSpace: xiaobao-namespace