spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/keshexiaobao?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  elasticsearch:
    host: localhost
    port: 9200
  data:
    #    mongodb数据库
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db

#阿里百炼大模型
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-401f04bff45540b1b7e818282e32127a
        model-name: qwen-flash
      embedding-model:
        api-key: sk-401f04bff45540b1b7e818282e32127a
        model-name: text-embedding-v4
      streaming-chat-model:
        api-key: sk-401f04bff45540b1b7e818282e32127a
        model-name: qwen-flash

#pinecone向量数据库
pineconeEmbeddingStore:
  apiKey: pcsk_6g1dju_7M1KqE1B5hnTwCnPZTHZmfw8YYqsEpzixmTs2qMsGpD2HHSrfeV8diqkRSydNfQ
  index: keshe
  nameSpace: xiaobao-namespace

management:
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
    rabbit:
      enabled: false
